### ISSUE TITLE
WiFi hotspot is broken

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#53]
It has been confirmed that WiFi hotspot is broken. Not too sure if the WiFi driver update caused this issue. CM13 stock kernel works fine, so I guess we may be missing something.

**Comment by gsstudios** [comment]
Here is a log:
http://forum.xda-developers.com/showpost.php?p=67695368&postcount=1133

**Comment by Realex-fire** [comment]
The problem definitely is in the new wifi driver. (hostapd : Could not set channel for kernel driver)

EDIT: Probably we still have a problem with Xposed application, it is worth writing on xda that it can't be used with our kernel. (it is necessary to understand because of what there are problems.)

**Comment by Realex-fire** [comment]
@gsstudios 
I have looked into our wifi driver before upgrade, it was a lot of fixes from  StanTRC and Dorimanx, I think we should temporarily revert to the old driver because the new driver has problems, we ignore changes which were already in the kernel.
It will be the simplest and right decision. further it will be necessary to return to it.

**Comment by Realex-fire** [comment]
I returned to old wifi driver, everything works at it. All changes in my git repo.

**Comment by gsstudios** [comment]
No worries. Looks like it will be a lot of work to get new driver working fully.

**Comment by Realex-fire** [comment]
I was able to fix it ;) Pull Request: https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/pull/54

**Comment by gsstudios** [comment]
Solved in 12.0 b005
