### ISSUE TITLE
Get xposed to work on this kernel

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#55]
Xposed seems to be broken when this kernel is installed. CM13 stock kernel doesn't have the same problem.

**Comment by gsstudios** [comment]
According to reports, it seems that xposed is working if installed as systemless with systemless SuperSU.

**Comment by Realex-fire** [comment]
For me system xposed and systemless xposed works well. (last cm13) Logcat clean.  I don't know why it doesn't work for other people... You checked it ? Your logcat without errors ?
Edit:
`cutils-trace error opening trace file permission denied (13)` - I have only such. but it is not errors, it warnings because of the disabled trace in kernel.

**Comment by gsstudios** [comment]
I'll have to ask users again if they face such issues.

**Comment by gsstudios** [comment]
I think this can be closed.
